services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
    secrets:
      - mongo_root_user
      - mongo_root_password

  janux_auth_gateway:
    build:
      context: .
    container_name: janux_auth_gateway
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: production
      MONGO_URI: mongodb://$(cat /run/secrets/mongo_root_user):$(cat /run/secrets/mongo_root_password)@mongodb:27017
      AUTH_SECRET_KEY_FILE: /run/secrets/auth_secret_key
    secrets:
      - auth_secret_key
    depends_on:
      - mongodb

secrets:
  mongo_root_user:
    file: ./secrets/mongo_root_user.txt
  mongo_root_password:
    file: ./secrets/mongo_root_password.txt
  auth_secret_key:
    file: ./secrets/auth_secret_key.txt
