services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  janux_auth_gateway:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://root:password@mongodb:27017
      AUTH_SECRET_KEY: your_secret_key
    depends_on:
      - mongodb
