
services:
  janux-auth-gateway:
    image: janux-auth-gateway:latest
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    environment:
      ENVIRONMENT: "test"
      AUTH_DB_BACKEND: "postgres"
      POSTGRES_DATABASE_NAME: "users_db"
      POSTGRES_ECHO: "false"
      POSTGRES_POOL_SIZE: "5"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      ALLOWED_ORIGINS: "*"
      ACCESS_TOKEN_EXPIRE_MINUTES: "20"
      TOKEN_ISSUER: "JANUX-server"
      TOKEN_AUDIENCE: "JANUX-application"
      USER_TOKEN_URL: "/auth/login"
      ADMIN_TOKEN_URL: "/auth/login"
    secrets:
      - janux_encryption_key
      - jwt_private_key
      - jwt_public_key
      - postgres_uri
      - postgres_admin_username
      - postgres_admin_password
      - postgres_admin_fullname
      - postgres_admin_role
      - postgres_user_username
      - postgres_user_password
      - postgres_user_fullname
      - postgres_user_role
    networks:
      - janux-network

  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER_FILE: /run/secrets/postgres_admin_username
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_admin_password
    secrets:
      - postgres_admin_username
      - postgres_admin_password
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init..sql:ro
      - postgres-data:/var/lib/postgresql/data
    networks:
      - janux-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fox-techniques.com
      PGADMIN_DEFAULT_PASSWORD: Pa55w0rd!
    depends_on:
      - postgres
    networks:
      - janux-network

  redis:
    image: redis:latest
    networks:
      - janux-network

networks:
  janux-network:
    external: true

volumes:
  postgres-data:

secrets:
  janux_encryption_key:
    external: true
  jwt_private_key:
    external: true
  jwt_public_key:
    external: true
  postgres_uri:
    external: true
  postgres_admin_username:
    external: true
  postgres_admin_password:
    external: true
  postgres_admin_fullname:
    external: true
  postgres_admin_role:
    external: true
  postgres_user_username:
    external: true
  postgres_user_password:
    external: true
  postgres_user_fullname:
    external: true
  postgres_user_role:
    external: true
