
services:
  janux-auth-gateway:
    image: janux-auth-gateway:latest
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      ENVIRONMENT: "test"
      AUTH_DB_BACKEND: "mongo"
      MONGO_DATABASE_NAME: "users_db"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      ALLOWED_ORIGINS: "*"
      ACCESS_TOKEN_EXPIRE_MINUTES: "20"
      TOKEN_ISSUER: "JANUX-server"
      TOKEN_AUDIENCE: "JANUX-application"
      USER_TOKEN_URL: "/auth/login"
      ADMIN_TOKEN_URL: "/auth/login"
    secrets:
      - janux_encryption_key
      - jwt_private_key
      - jwt_public_key
      - mongo_uri
      - mongo_admin_email
      - mongo_admin_password
      - mongo_admin_fullname
      - mongo_admin_role
      - mongo_user_email
      - mongo_user_password
      - mongo_user_fullname
      - mongo_user_role
    networks:
      - janux-network

  mongodb:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: users_db
    networks:
      - janux-network

  redis:
    image: redis:latest
    networks:
      - janux-network

networks:
  janux-network:
    external: true

volumes:
  mongo-data:

secrets:
  janux_encryption_key:
    external: true
  jwt_private_key:
    external: true
  jwt_public_key:
    external: true
  mongo_uri:
    external: true
  mongo_admin_email:
    external: true
  mongo_admin_password:
    external: true
  mongo_admin_fullname:
    external: true
  mongo_admin_role:
    external: true
  mongo_user_email:
    external: true
  mongo_user_password:
    external: true
  mongo_user_fullname:
    external: true
  mongo_user_role:
    external: true
