name: Publish Material Docs to GitHub Pages

on:
  push:
    branches: 
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: release-with-approval

    permissions:
      contents: read   
      packages: write  
      id-token: write  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from Git tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/janux-auth-gateway:${{ env.VERSION }} .
          docker tag ghcr.io/${{ github.repository_owner }}/janux-auth-gateway:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/janux-auth-gateway:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/janux-auth-gateway:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/janux-auth-gateway:latest
